### ISSUE TITLE
Python SLEEPPY demo gets IOError: “sleep_endpoints_summary.csv does not exist”

### ISSUE THREAD

**Issue by ghost** [elyiorgos/sleeppy#8]
Full error is:
IOError: File C:\PRIMARY\WORK\wearable\SLEEPPY\RESULTS/demo/sleep_endpoints/sleep_endpoints_summary.csv does not exist

What's up with backslashes and then foreslashes?

...and it is missing directory:   SLEEPPY\RESULTS/demo/
C:\PRIMARY\WORK\wearable\SLEEPPY\RESULTS\ exists.

I get the IOError when I do "Running the demo files" after I installed https://github.com/elyiorgos/sleeppy .

I'm running on Windows 10 Python 2.7.18

Full output, with error at end...

>>> import sleeppy.tests as demo
>>> demo.run_demo()
Please provide a path to a results directory:    C:\PRIMARY\WORK\wearable\SLEEPPY\RESULTS
Loading data...
Error processing: c:\Python27\lib\site-packages\sleeppy\tests\demo.bin
Error: ``C:\PRIMARY\WORK\wearable\SLEEPPY\RESULTS/c:\Python27\lib\site-packages\sleeppy\tests\demo/raw_days/c:\Python27\lib\site-packages\sleeppy\tests`` does not exist
total run time: 6.7197999994 minutes
Checking endpoints...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\sleeppy\tests\demo.py", line 37, in run_demo
    obtained = collect_endpoints(dst)
  File "c:\Python27\lib\site-packages\sleeppy\tests\demo.py", line 43, in collect_endpoints
    return pd.read_csv(src).values[0]
  File "c:\Python27\lib\site-packages\pandas\io\parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "c:\Python27\lib\site-packages\pandas\io\parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "c:\Python27\lib\site-packages\pandas\io\parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "c:\Python27\lib\site-packages\pandas\io\parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "c:\Python27\lib\site-packages\pandas\io\parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas\_libs\parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
IOError: File C:\PRIMARY\WORK\wearable\SLEEPPY\RESULTS/demo/sleep_endpoints/sleep_endpoints_summary.csv does not exist
>>>

**Comment by agpr141** [comment]
Did you ever solve this? I assume this package isn't maintained. I also got the same error when trying to run the demo
Cheers

**Comment by 0xBADBAC0N** [comment]
This is due to a mixup of the pathes. The code itself is most likely written and tested under Linux, If you are a windows user, you can either fix the source code or run that code for example in a VM or something similar like WSL
